language: python

os:
  - linux

python:
  - 3.6

addons:
  apt:
    packages:
    - python-setuptools

install:
  - pip install awkward
  - pip install uproot
  - pip install numpy --upgrade
  - pip install numba
  - pip install psutil
  - pip install matplotlib
  - pip install scipy
  - pip install requests
  - pip install cffi
  - pip install pyyaml
  - pip install lz4 cloudpickle tqdm six futures
  - pip install keras tensorflow==1.15

script:
    - PYTHONPATH=coffea:hepaccelerate:. python tests/hmm/hmumu_utils.py
    - PYTHONPATH=coffea:hepaccelerate:. python tests/hmm/test_hmumu_utils.py
