language: python

os:
  - linux

python:
  - 3.6

addons:
  apt:
    packages:
    - python-setuptools

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda create -n myenv
  - conda activate myenv
  - conda install awkward cffi cloudpickle lz4 numba numpy psutil python-xxhash pyyaml requests root scipy six tbb tqdm uproot xxhash
  - pip install tensorflow keras


script:
    - PYTHONPATH=coffea:hepaccelerate:. python tests/hmm/hmumu_utils.py
    - PYTHONPATH=coffea:hepaccelerate:. python tests/hmm/test_hmumu_utils.py
    - PYTHONPATH=coffea:hepaccelerate:. python tests/hmm/test_analysis_full.py
