language: python

os:
  - linux

python:
  - 3.6

addons:
  apt:
    packages:
    - python-setuptools

install:
  - pip install awkward
  - pip install uproot
  - pip install numpy --upgrade
  - pip install numba
  - pip install psutil
  - pip install matplotlib
  - pip install scipy
  - pip install git+https://github.com/hepaccelerate/hepaccelerate
  - pip install coffea

script:
    - PYTHONPATH=. python tests/hmm/hmumu_utils.py
