language: python

os:
  - linux

python:
  - 3.6

addons:
  apt:
    packages:
    - python-setuptools

install:
  - pip install awkward
  - pip install uproot
  - pip install numpy --upgrade

script:
    - PYTHONPATH=. python tests/example.py
